BAN-2749:  Update Borrow UI / UX (Token lending)
frakt-solana/banx-ui pull request #1023
Opened 2024-10-17 17:03 UTC by iamsphere

## Issue link

https://linear.app/banx-gg/issue/BAN-2749/fe-banx-update-borrow-ui-ux-token-lending

## Vercel preview

https://banx-ui-git-bugfix-ban-2749-frakt.vercel.app/

2024-10-30 11:55 UTC, sablevsky requested changes

2024-10-30 13:22 UTC, iamsphere commented on src/utils/core/tokenLoans/index.ts
> +    : BASE_POINTS_BN.sub(PROTOCOL_FEE_TOKEN_BN)
Да, это нужно, чтобы правильно получить финальный результат. Мы подгоняем Required Amount с учетом upfront fee и уже на основе этого собираем корзину. Тогда финальная сумма, например, если хотели получить 10$, действительно будет 10$. Без upfront итог выйдет меньше.

2024-10-30 13:26 UTC, iamsphere commented on package.json
> +    "solana-transactions-parser": "^2.0.2",
Updated

2024-10-30 13:32 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/constants.ts
> +export const MAX_TOKEN_TO_GET_TRESHOLD = 100
5758082d46e04e11b7d3cbb3f5eb2d7d6d796695

2024-10-30 14:33 UTC, iamsphere commented on src/utils/core/tokenLoans/index.ts
> +    : BASE_POINTS_BN.sub(PROTOCOL_FEE_TOKEN_BN)
1ea6e75a62a1de57e89345a2824a13bc0b533933

2024-10-31 09:24 UTC, sablevsky approved these changes

2024-10-31 09:46 UTC, merged