Feature/lend-page
frakt-solana/banx-ui pull request #11
Opened 2023-08-14 08:29 UTC by iamsphere

2023-08-16 15:52 UTC, sablevsky requested changes

2023-08-16 15:52 UTC, sablevsky commented on src/components/SearchSelect/SearchSelect.tsx
> +  }
Оберка на будущее? Просто пока в ней нет смысла особого

2023-08-16 15:52 UTC, sablevsky commented on src/components/inputs/InputErrorMessage.tsx
> +}
Полагаю, так сделано, чтоб резервировать место в разметке и чтоб не прыгало ничего, верно?
Но мне кажется, что одного пропа message было б достаточно. Зачем еще доп флаг hasError?

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +enum TabsNames {
лучше TabName.
Т.к. когда enum выступает типом, то лучше чтоб оно было в едиснтсвенном числе.
Array<TabNames>, например, звучит нелепо и вводит в заблуждение. Кажется, что это двумерный массив

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +  visibleOrderBook: boolean
isOrderBookVisible может лучше?

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +  const tabsComponents: TabsComponents = {
Константа

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/LendCard/LendCard.tsx
> +  cardIsOpen: boolean
isCardOpen лучше

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/LendCard/LendCard.tsx
>    visibleOrderBook: boolean
isOrderBookVisible

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/LendPageContent/constants.ts
> +export const sortOptions = [
Константа

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/LendPageContent/constants.ts
> +export const defaultSortOption = { label: 'Loans TVL', value: 'loansTVL_desc' }
Константа

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/OrderBook/components.tsx
> +    <div className={styles.noDataSubtitle}>Good chance to be first!</div>
а можно хотя б <p> вместо дивов?)

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/OrderBook/hooks/useMarketOrders.ts
> +    return orders
Можно сразу return сделать

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/PlaceOfferTab/components.tsx
> +  const weeklyAprPercentage = marketAPR / 100 / 52
я б 52 в константу вынес, чтоб понятно было, что это количество недель

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/PlaceOfferTab/hooks/useOfferFormController.ts
> +  initialLoansAmount: number = 1,
Типы не нужны, если есть дефолтные значения

2023-08-16 15:52 UTC, sablevsky commented on src/pages/LendPage/components/PlaceOfferTab/hooks/usePlaceOfferTab.ts
> +import { parseMarketOrder } from '../../OrderBook/helpers'
Тут лучше использовать импорты с @banx

2023-08-17 07:10 UTC, iamsphere commented on src/Layout/Layout.tsx
> +    <div className={styles.layout} id="app-content">
Да, больше не нужен, убрал

2023-08-17 07:10 UTC, iamsphere commented on src/components/PageHeader/PageHeader.module.less
> +  width: 0.5px;
Обсудили, оставил

2023-08-17 07:11 UTC, iamsphere commented on src/components/inputs/InputErrorMessage.tsx
> +}
Да, верно.
Не очень нравилось прокидывать message как {error ? 'error message' : ""}. 
Флаг hasError убрал

2023-08-17 07:12 UTC, iamsphere commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +enum TabsNames {
Согласен, поменял

2023-08-17 07:12 UTC, iamsphere commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +  visibleOrderBook: boolean
да, поменял

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/ExpandableCardContent/ExpandableCardContent.tsx
> +  const tabsComponents: TabsComponents = {
Сделал

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/LendCard/LendCard.tsx
> +  cardIsOpen: boolean
Поменял

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/LendCard/LendCard.tsx
>    visibleOrderBook: boolean
Поправил

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/LendPageContent/constants.ts
> +export const sortOptions = [
Сделал

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/LendPageContent/constants.ts
> +export const defaultSortOption = { label: 'Loans TVL', value: 'loansTVL_desc' }
Сделал

2023-08-17 07:13 UTC, iamsphere commented on src/pages/LendPage/components/OrderBook/components.tsx
> +    <div className={styles.noDataSubtitle}>Good chance to be first!</div>
Да, зажестил) Исправил

2023-08-17 07:14 UTC, iamsphere commented on src/pages/LendPage/components/OrderBook/hooks/useMarketOrders.ts
> +    return orders
Можно, сделал

2023-08-17 07:14 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/components.tsx
> +  const weeklyAprPercentage = marketAPR / 100 / 52
Вынес

2023-08-17 07:14 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/useOfferFormController.ts
> +  initialLoansAmount: number = 1,
Согласен, убрал

2023-08-17 07:15 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/usePlaceOfferTab.ts
> +import { parseMarketOrder } from '../../OrderBook/helpers'
Не согласен, import @banx/pages/LendPage/components/... выглядит куда страшнее, чем то, что сейчас)

2023-08-17 09:57 UTC, sablevsky commented on src/pages/LendPage/components/PlaceOfferTab/hooks/usePlaceOfferTab.ts
> +import { parseMarketOrder } from '../../OrderBook/helpers'
Не заметил, что компоненты внутри одной страницы, ок, вопросов нет

2023-08-17 09:59 UTC, merged