Refactor Dashboard components
frakt-solana/banx-ui pull request #135
Opened 2023-09-30 11:02 UTC by iamsphere

## Description

Simplify dashboard components, improve readable 

## Screenshots

## Issue link

https://linear.app/banx-gg/issue/BAN-1205/fe-refactor-dashboard-components

## Vercel preview

https://banx-ui-git-feature-ban-1205-frakt.vercel.app/

2023-10-02 18:12 UTC, sablevsky requested changes

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/AvailableToBorrow/AvailableToBorrow.tsx
> +        )}
Давай лучше вместо тернарника сделаем 2 проверки:
!!isConnected && <Component1>
!isConnected && <Component2>

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +const CardList = () => {
Может лучше CardsList?

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +            ))}
Тут тоже, 2 проверки читаются лучше чем тернарник, как по мне

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +  const bestOffer = findBestOffer(loan.marketPubkey)
Мб useMemo? Сложная операция

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/MyLoans/constants.ts
> +export const NO_DATA_CHART = {
NO_DATA_CHART_DATA?

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/constants.ts
> +export const NO_DATA_CHART = {
NO_DATA_CHART_DATA?

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/AllTimeBlock.module.less
> +  height: 100%;
Тут ты что-то с высотами перемудрил, не?

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/hooks.ts
> +  const { totalRepaid = 0, totalDefaulted = 0 } = stats || {}
Тут не нужно оформлять как хук, у тебя ж стейта нет никакого. Просто функция должна быть

2023-10-02 18:12 UTC, sablevsky commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllocationBlock/constants.ts
> +export const NO_DATA_CHART = {
NO_DATA_CHART_DATA?

2023-10-03 16:53 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/MyLoans/constants.ts
> +export const NO_DATA_CHART = {
Да, можно и такой нейминг, поправил
 https://github.com/frakt-solana/banx-ui/pull/135/commits/8fd6d18ec6b626637bff491a94bb3724b3504e37

2023-10-03 16:53 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/constants.ts
> +export const NO_DATA_CHART = {
https://github.com/frakt-solana/banx-ui/pull/135/commits/8fd6d18ec6b626637bff491a94bb3724b3504e37

2023-10-03 16:54 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/AllTimeBlock.module.less
> +  height: 100%;
Да, убрал min width  https://github.com/frakt-solana/banx-ui/pull/135/commits/88880bc3e903254d614b655be4a54ac7ecb1e6a3

2023-10-03 16:55 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllTimeBlock/hooks.ts
> +  const { totalRepaid = 0, totalDefaulted = 0 } = stats || {}
Полностью согласен, переписал https://github.com/frakt-solana/banx-ui/pull/135/commits/fb4c3ba94fd3dfd349fc511390f3488ce3f9b0de

2023-10-03 16:55 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardLendTab/components/AllocationBlock/constants.ts
> +export const NO_DATA_CHART = {
https://github.com/frakt-solana/banx-ui/commit/8fd6d18ec6b626637bff491a94bb3724b3504e37

2023-10-03 16:56 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +  const bestOffer = findBestOffer(loan.marketPubkey)
Добавил https://github.com/frakt-solana/banx-ui/pull/135/commits/089a4bc0b61398cd8348cd49843af6fe4f155960

2023-10-03 16:57 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +            ))}
Поправил

2023-10-03 16:57 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/AvailableToBorrow/AvailableToBorrow.tsx
> +        )}
Поправил

2023-10-03 16:58 UTC, iamsphere commented on src/pages/DashboardPage/components/DashboardBorrowTab/components/CardList.tsx
> +const CardList = () => {
Поменял https://github.com/frakt-solana/banx-ui/pull/135/commits/b8ed6a998455a97f91dbd2f7908e898257db3682

2023-10-03 17:00 UTC, iamsphere commented
И давай отдадим на ретесты после апрува

2023-10-04 08:08 UTC, sablevsky approved these changes

2023-10-05 14:37 UTC, merged