Add "No activity" states to Lend page, fix bottom fixed empty block
frakt-solana/banx-ui pull request #195
Opened 2023-10-15 21:56 UTC by iamsphere

## Description

Add "No activity" states to Lend page (both all and personal)
Fixed bottom fixed empty block

## Screenshots

<img width="934" alt="image" src="https://github.com/frakt-solana/banx-ui/assets/60342317/c21f83ec-aac7-4e90-88ba-db9fb4efad14">

## Issue link

https://linear.app/banx-gg/issue/BAN-1297/fe-banx-bottom-fixed-empty-block
https://linear.app/banx-gg/issue/BAN-1295/fe-add-no-activity-states-to-lend-page-both-all-and-personal

## Vercel preview

https://banx-ui-git-feature-ban-1295-frakt.vercel.app/

2023-10-15 22:30 UTC, sablevsky requested changes

2023-10-15 22:30 UTC, sablevsky commented on src/components/EmptyList/EmptyList.tsx
> +  onClick?: () => void
Давай лучше сделаем какой-нибудь проп для кнопки отдальный:
bottomButtonProps: {text, onClick}. Чтоб отказаться от path и buttonText

2023-10-15 22:30 UTC, sablevsky commented on src/pages/LendPage/LendPage.tsx
> +    <>
Зачем удалил? Оно нужно, попробуй сайдер с нотификациями открыть и поскроллить -- увидишь, для чего был нужен этот стиль

2023-10-15 22:32 UTC, sablevsky commented on src/pages/LendPage/LendPage.tsx
> +    <>
<img width="1512" alt="image" src="https://github.com/frakt-solana/banx-ui/assets/24393100/b089a63b-e4d0-418b-8309-404dcc5e5357">

2023-10-15 22:33 UTC, iamsphere commented on src/pages/LendPage/LendPage.tsx
> +    <>
Опа, вот это приколы)

2023-10-15 23:14 UTC, iamsphere commented on src/components/EmptyList/EmptyList.tsx
> +  onClick?: () => void
Да, так определенно лучше будет
Сделал

2023-10-15 23:17 UTC, iamsphere commented on src/pages/LendPage/LendPage.tsx
> +    <>
Вернул
Все-таки фикс со сломанным лейаутом, после нажатий на несколько чекбоксов, сделаю в другой таске
Не супер очевидный баг (Пока не разобрался)

2023-10-16 01:17 UTC, sablevsky requested changes

2023-10-16 01:17 UTC, sablevsky commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useLoansActiveTable.ts
> +    },
Лучше `buttonProps: connected ? {text: 'borrow', onClick: goToBorrowPage} : undefined`

2023-10-16 01:17 UTC, sablevsky commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useLoansActiveTable.ts
> +    },
Везде поменять надо

2023-10-16 01:17 UTC, sablevsky commented on src/components/EmptyList/EmptyList.tsx
> +    onClick?: () => void
onClick сделать required, т.к. какой смысл в кнопке без onClick?

2023-10-16 08:47 UTC, iamsphere commented on src/components/EmptyList/EmptyList.tsx
> +    onClick?: () => void
https://github.com/frakt-solana/banx-ui/pull/195/commits/72fa1f00feb3a57880c497086ace38503249fe4a

2023-10-17 11:26 UTC, merged