BAN-1470: Implement Pro UI (bonding curve) on Lend Page
frakt-solana/banx-ui pull request #280
Opened 2023-11-01 10:49 UTC by iamsphere

## Description

Implement Pro UI (bonding curve) on Lend Page

## Screenshots

## Issue link

https://linear.app/banx-gg/issue/BAN-1470/fe-banx-implement-pro-ui-bonding-curve-on-lend-page

## Vercel preview

2023-11-21 15:18 UTC, sablevsky requested changes

2023-11-22 06:37 UTC, iamsphere commented on src/transactions/loans/makeRepayPartialLoanAction.ts
> +type OptimisticResult = BondAndTransactionOptimistic & { oldBondOffer: BondOfferV2 }
Спулился

2023-11-22 06:38 UTC, iamsphere commented on src/store/offers/useSyntheticOffers.ts
> +  deltaValue?: number //? exist only in pro mode
[Add delta and mathCounter as required field, set 0 as default](https://github.com/frakt-solana/banx-ui/pull/280/commits/4ee397272a0804ac8abaac6e6a966bb06fc0f10e)
Сделал

2023-11-22 06:38 UTC, iamsphere commented on src/store/offers/useSyntheticOffers.ts
> +  mathCounter?: number
[Add delta and mathCounter as required field, set 0 as default](https://github.com/frakt-solana/banx-ui/pull/280/commits/4ee397272a0804ac8abaac6e6a966bb06fc0f10e)

2023-11-22 06:38 UTC, iamsphere commented on src/store/offers/useSyntheticOffers.ts
> +  mathCounter: 0,
[Add delta and mathCounter as required field, set 0 as default](https://github.com/frakt-solana/banx-ui/pull/280/commits/4ee397272a0804ac8abaac6e6a966bb06fc0f10e)

2023-11-22 06:39 UTC, iamsphere commented on src/store/offers/useSyntheticOffers.ts
> +    mathCounter,
[Add delta and mathCounter as required field, set 0 as default](https://github.com/frakt-solana/banx-ui/pull/280/commits/4ee397272a0804ac8abaac6e6a966bb06fc0f10e)

2023-11-22 06:39 UTC, iamsphere commented on src/store/offers/useSyntheticOffers.ts
> +  } = offer
[Add delta and mathCounter as required field, set 0 as default](https://github.com/frakt-solana/banx-ui/pull/280/commits/4ee397272a0804ac8abaac6e6a966bb06fc0f10e)

2023-11-22 06:40 UTC, iamsphere commented on src/transactions/bonds/makeCreateBondingOfferAction.ts
> +  loanValue: number //? value in sol
https://github.com/frakt-solana/banx-ui/pull/280/commits/49321c8b2e52fd434cabac8f5af38ff884e5ea0e
Помел тут

2023-11-22 06:40 UTC, iamsphere commented on src/transactions/bonds/makeUpdateBondingOfferAction.ts
> +  loanValue: number //? value in sol
https://github.com/frakt-solana/banx-ui/pull/280/commits/49321c8b2e52fd434cabac8f5af38ff884e5ea0e
Поменял тут

2023-11-22 06:40 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceProOffer/components.tsx
> +type CalculateWeightedWeeklyInterest = (offerSize: number, marketApr: number) => number
https://github.com/frakt-solana/banx-ui/pull/280/commits/49321c8b2e52fd434cabac8f5af38ff884e5ea0e
Поправил

2023-11-22 06:58 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/PlaceLiteOffer.tsx
> +        {...offerTransactions}
[Remove spread for better readability](https://github.com/frakt-solana/banx-ui/pull/280/commits/e1d9f0681aa8ff4a75573d859fc351fe46070041)

2023-11-22 06:59 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceProOffer/PlaceProOffer.tsx
> +        {...offerTransactions}
[Remove spread for better readability](https://github.com/frakt-solana/banx-ui/pull/280/commits/e1d9f0681aa8ff4a75573d859fc351fe46070041)

2023-11-22 06:59 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/usePlaceOffer.ts
> +  const { offerMode, marketPubkey, onChangeOfferMode, setOfferPubkey, offerPubkey } = props || {}
[Remove unnecessary nullish coalescing in prop destructuring](https://github.com/frakt-solana/banx-ui/pull/280/commits/d7409ab139686777b237df27366f6ad3c78b973e)

2023-11-22 06:59 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/usePlaceOffer.ts
> +type UsePlaceOffer = (props: OrderBookMarketParams) => OfferParams & { offerMode: OfferMode }
d7409ab139686777b237df27366f6ad3c78b973e

2023-11-22 07:00 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/components.tsx
> +  const displayOfferSize = offerSize ? formatDecimal(offerSize) : 0
[convert variables to one type](https://github.com/frakt-solana/banx-ui/pull/280/commits/5da42324c22f0627389a161d892474ac2a385eb5)

2023-11-22 07:00 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/components.tsx
> +  const displayEstimatedInterest = estimatedInterest ? formatDecimal(estimatedInterest) : 0
[convert variables to one type](https://github.com/frakt-solana/banx-ui/pull/280/commits/5da42324c22f0627389a161d892474ac2a385eb5)

2023-11-22 07:01 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/helpers.ts
> +  const defaultLoanValue = Math.min(maxLoanValue, bestOfferInSol) || 0
[Remove unnecessary default value in bestOfferInSol calculation](https://github.com/frakt-solana/banx-ui/pull/280/commits/cabc39807f4c4e55267e74b87bc505d124dcd2df)

2023-11-22 07:23 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/PlaceLiteOffer.tsx
> +          hasError
Убрал в этом коммите
e1d9f0681aa8ff4a75573d859fc351fe46070041

2023-11-22 07:24 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceLiteOffer/helpers.ts
> +const TRANSACTION_FEE_IN_SOL = 0.01
Можно попробовать и меньше, но 0.01 запревентит любые кейсы с "not enough sol"

2023-11-22 07:34 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/useOfferTransactions.ts
>    const onCreateOffer = async () => {
[Remove old onCreateOffer, onUpdateOffer functions](https://github.com/frakt-solana/banx-ui/pull/280/commits/502b08c409bab1d4902c4cca6f2658647a6159b3)

2023-11-22 07:34 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/useOfferTransactions.ts
> +  const onUpdateOffer = async () => {
[Remove old onCreateOffer, onUpdateOffer functions](https://github.com/frakt-solana/banx-ui/pull/280/commits/502b08c409bab1d4902c4cca6f2658647a6159b3)

2023-11-22 07:35 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/hooks/useOfferTransactions.ts
> +const showSuccessSnackbar = ({ message, txnHash }: { message: string; txnHash: string }) => {
Убрал вообще эту функцию
[Remove old onCreateOffer, onUpdateOffer functions](https://github.com/frakt-solana/banx-ui/pull/280/commits/502b08c409bab1d4902c4cca6f2658647a6159b3)

2023-11-22 07:35 UTC, iamsphere commented on src/pages/LendPage/components/PlaceOfferTab/PlaceOfferTab.tsx
> +  const isEditMode = !!offerPubkey && offerPubkey !== PUBKEY_PLACEHOLDER
В 2х местах используется, думаю пока можно не выносить

2023-11-22 07:51 UTC, iamsphere commented on src/pages/LendPage/components/OrderBook/OrderBook.module.less
> +  min-width: 296px;
[Remove css calculations in OrderBook.module.less](https://github.com/frakt-solana/banx-ui/pull/280/commits/d32327d8dd6235322c72425aed829c9740f380bd)

2023-11-22 08:07 UTC, iamsphere commented on src/utils/common.ts
> +  if (!value) return '0'
[Modify formatDecimal, getDecimalPlaces functions](https://github.com/frakt-solana/banx-ui/pull/280/commits/9f3b192b965473920752eed0090c58b292a18515)

2023-11-22 11:05 UTC, sablevsky commented on src/pages/LendPage/components/PlaceOfferTab/PlaceOfferTab.tsx
> +  const isEditMode = !!offerPubkey && offerPubkey !== PUBKEY_PLACEHOLDER
Оке

2023-11-22 11:06 UTC, sablevsky approved these changes

2023-11-22 11:07 UTC, merged