Implement virtualization for large lists insted of infinite scroll
frakt-solana/banx-ui pull request #291
Opened 2023-11-06 12:03 UTC by sablevsky

## Issue link

https://linear.app/banx-gg/issue/BAN-1337/fe-rnd-implement-virtualization-for-large-lists-insted-of-infinite

## Vercel preview

https://banx-ui-git-feature-ban-1337-frakt.vercel.app/

2023-11-06 13:11 UTC, iamsphere approved these changes

2023-11-08 08:49 UTC, iamsphere requested changes

2023-11-08 08:49 UTC, iamsphere commented on src/components/Table/types.ts
> +  showSorterTooltip?: boolean //? Legacy prop
showSorterTooltip использовался в ant design таблицах чтобы убирать тултип, который под дефолту true. Сейчас он не нужен, можно убрать.

2023-11-08 08:49 UTC, iamsphere commented on src/components/Table/types.ts
> +  sorter?: boolean //? Legacy prop
Sorter не легаси проп
Если "sorter: true", то эта колонка добавляется в sortDropdown

2023-11-08 08:49 UTC, iamsphere commented on src/components/Table/views/CardView/CardView.tsx
> +export const CardView = <T extends object>({
Если у колонки есть кнопка, необходимо скрыть label

<img width="912" alt="image" src="https://github.com/frakt-solana/banx-ui/assets/60342317/03848458-a483-483e-a9f7-14f8a5a3b17d">

2023-11-08 11:43 UTC, sablevsky commented on src/components/Table/views/CardView/CardView.tsx
> +export const CardView = <T extends object>({
Не знаю, откуда вылезло, т.к. ничего не менял, вроде.
Пофиксил следующим образом: https://github.com/frakt-solana/banx-ui/pull/291/commits/b4507eda5937077b5c4371c6903e5810df3680fc

2023-11-08 11:49 UTC, iamsphere approved these changes

2023-11-08 18:57 UTC, merged