BAN-1574: Sort terminating loans by time
frakt-solana/banx-ui pull request #337
Opened 2023-11-16 13:13 UTC by iamsphere

## Description

[Rewrite loans sorting](https://github.com/frakt-solana/banx-ui/commit/4d85ea9a2d1c5f8e25a933272abd989148e4a253)
[Set fixed width for loans cells](https://github.com/frakt-solana/banx-ui/commit/0f9a5cf28b1c635cf8ecdde931f5da5d62787e59)

## Screenshots

<img width="1291" alt="image" src="https://github.com/frakt-solana/banx-ui/assets/60342317/6ab275d6-055e-47df-a65f-8b7c4faa1aa4">

## Issue link

https://linear.app/banx-gg/issue/BAN-1574/fe-banx-sort-terminating-loans-by-time

## Vercel preview

https://banx-ui-git-feature-ban-1574-frakt.vercel.app/

2023-11-16 23:08 UTC, sablevsky requested changes

2023-11-16 23:08 UTC, sablevsky commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useSortedLoans.ts
> +  })
Давай везде сделаем функции в STATUS_VALUE_MAP, чтоб не было этой проверки на isFunction и юнион типа

2023-11-16 23:08 UTC, sablevsky commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useSortedLoans.ts
> +  const finalSortedOtherLoans = sortBy(otherLoans, 'fraktBond.activatedAt').reverse()
Это лучше через lodash. chain сделать, может? Чтоб более целостно смортелось

2023-11-17 08:38 UTC, iamsphere commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useSortedLoans.ts
> +  const finalSortedOtherLoans = sortBy(otherLoans, 'fraktBond.activatedAt').reverse()
Переписал, сейчас должно быть лучше https://github.com/frakt-solana/banx-ui/pull/337/commits/3a822795dd2bbe94a195c892cd45454d3f630a8a

2023-11-17 08:38 UTC, iamsphere commented on src/pages/LoansPage/components/LoansActiveTable/hooks/useSortedLoans.ts
> +  })
Поправил https://github.com/frakt-solana/banx-ui/pull/337/commits/3a822795dd2bbe94a195c892cd45454d3f630a8a

2023-11-17 14:22 UTC, sablevsky approved these changes

2023-11-20 11:14 UTC, merged