BAN-2157
frakt-solana/banx-ui pull request #617
Opened 2024-02-29 11:30 UTC by QuadradS

- new token staking ui

## Description

Token and nfrts staking

## Issue link

[
](https://linear.app/banx-gg/issue/BAN-2157/create-staking-ui)

2024-03-18 11:22 UTC, iamsphere requested changes

2024-03-18 11:22 UTC, iamsphere commented on src/pages/AdventuresPage/components/AdventuresList/components.tsx
> +export const AdventureSubscribeButton: FC<AdventuresComponentsProps> = () => {
А что за мертвая кнопка без onClick?

2024-03-18 11:22 UTC, iamsphere commented on src/transactions/banxStaking/unStakeBanxToken.ts
> +  const r = await unstakeBanxToken(params)
деструктуризацией может бы достал?

2024-03-18 11:22 UTC, iamsphere commented on src/transactions/banxStaking/stakeBanxNftsAction.ts
> +
У тебя в функции onStake, где используется stakeBanxNftAction,  уже обрабатывается этот момент

2024-03-18 11:22 UTC, iamsphere commented on src/transactions/adventures/helpers.ts
>    return nfts.reduce((acc, { meta }) => acc + Number(meta.partnerPoints), 0)
Зачем Number, если partnerPoints -- number и обязательный параметр? 
+ Лучше использовать _sumBy

2024-03-18 11:38 UTC, iamsphere requested changes

2024-03-18 12:50 UTC, QuadradS commented on src/transactions/banxStaking/stakeBanxNftsAction.ts
> +
нет, ts ругается поэтому пришлось добавить

2024-03-18 12:51 UTC, QuadradS commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +  const willGetPts = calcPts(value)
по моему все нормально

2024-03-18 13:03 UTC, sablevsky requested changes

2024-03-18 13:03 UTC, sablevsky commented on src/pages/AdventuresPage/state.ts
> +}))
Мне не очень нравится, когда в зустанде используются запросы. Я б делал через useQuery. У меня есть примеры с мутированием кэша

2024-03-18 13:06 UTC, sablevsky commented on src/pages/AdventuresPage/AdventuresPage.tsx
> зачем?

Декларативнее и короче

2024-03-18 15:04 UTC, QuadradS commented on src/transactions/banxStaking/unStakeBanxToken.ts
> +type Params = Parameters<typeof unstakeBanxToken>[0]
Там не экспортируется тип поэтому я так сделал

2024-03-19 08:53 UTC, sablevsky requested changes

2024-03-19 08:53 UTC, sablevsky commented on src/constants/common.ts
> +export const TOTAL_BANX_PTS = 483_480
Вот это тоже перенести в banxNfts я имел в виду)

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/AdventuresPage.tsx
> +import _ from 'lodash'
Лучше импортить деструктуризацией. Так тришейкинг нормально работает

2024-03-19 08:53 UTC, sablevsky commented on src/transactions/banxStaking/unstakeBanxNftsAction.ts
> +export type UnStakeBanxNftAction = MakeActionFn<
UnstakeBanxNftAction

2024-03-19 08:53 UTC, sablevsky commented on src/transactions/banxStaking/unstakeBanxNftsAction.ts
> +export type StakeBanxTokenActionParams = {
UnstakeBanxTokenActionParams

2024-03-19 08:53 UTC, sablevsky commented on src/transactions/banxStaking/unstakeBanxTokenAction.ts
> +export type StakeBanxTokenAction = MakeActionFn<
UnstakeBanxTokenAction

2024-03-19 08:53 UTC, sablevsky commented on src/transactions/banxStaking/unstakeBanxTokenAction.ts
> +export type StakeBanxTokenActionParams = {
UnstakeBanxTokenActionParams

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/helpers.ts
> +  return Number(balance?.value.amount || 0)
Там, вроде строка приходит, да?
Давай лучше через parseInt тогда сделаем

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/helpers.ts
> +  const _v = new BN(v) //
//
?

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/Sidebar/Sidebar.module.less
> +      font: var(--important-text-mds);
Вернулся mds?
Мы ж поправили это в основных ветках
Да и mds у тебя не определен

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/Sidebar/Sidebar.module.less
> +  }
тут тоже, mds, которого не существует

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/NftsStats.tsx
> +  )
Давай тоже через lodash sumBy сделаем. Не любим мы reduce для суммы)

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +import { unstakeBanxNftsAction } from '@banx/transactions/banxStaking/unstakeBanxNftsAction'
Давай эти типы ипортнем из @banx/transactions/banxStaking (index)

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +import { NftsStats } from '@banx/pages/AdventuresPage/components/StakeNftsModal/NftsStats'
Тут тоже давай что-то сделаем с импортами. Чтоб не было таких колбас.
Кстати, в слове Checkbox камелкейс не нужен. Переименуй, по возможности

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +  const onUnStake = () => {
OnUnstake

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +        })
Я б снек успеха лучше выкинул в  pfSuccessAll, т.к. юзеры стейкают свои нфт сотнями. Чтоб не плодить 100 снэков

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +        })
Тут то же самое про снэки

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +import { unstakeBanxTokenAction } from '@banx/transactions/banxStaking/unstakeBanxTokenAction'
Из @banx/transactions/banxStaking давай импорт

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/styled.module.less
Мы называем styles.module.less везде. Переименуй, пожалуйста

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +  const format = formatNumbersWithCommas
неужели так бесит длинное имя?
Тогда переименуй при импорте 
import {
  formatNumbersWithCommas as formatWithCommas,
} from '@banx/utils'

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +  const onUnStakeTokens = () => {
onUnstakeToken

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +      Number(fromDecimals(banxTokenSettings?.tokensStaked || 0)) < Number(value)
Вместо конструктора Number лучше использовать parseInt/parseFloat

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/components/StakeTokens/index.tsx
> +  }
второй if не нужен
    if (currentTabValue === ModalTabs.STAKE) {
      return void onStakeTokens()
    }
    return void onUnstake

2024-03-19 08:53 UTC, sablevsky commented on src/pages/AdventuresPage/helpers.ts
> +}
Давай в utils это вынесем. Только универсальнее, добавив параметр decimals = 9.
И кстати, new BN не кинет ошибку, если число не будет int?
Если кидает, то я б v в parseInt завернул, чтоб обрубать дробную часть

2024-03-19 11:33 UTC, iamsphere requested changes

2024-03-19 11:33 UTC, iamsphere commented on src/pages/AdventuresPage/components/StakeNftsModal/index.tsx
> +          onClick={currentTab === modalTabs[0].value && 'Stake' ? onStake : onUnStake}
Что за проверка на строку "Stake"? Не понял)

2024-03-20 10:41 UTC, QuadradS commented on src/pages/AdventuresPage/helpers.ts
> +}
Неа, он кинет ошибку если там nan

2024-03-25 12:57 UTC, merged