BAN-2188: Add boost (player pts) into wallet modal for each wallet
frakt-solana/banx-ui pull request #624
Opened 2024-03-04 14:48 UTC by iamsphere

## Description

## Screenshots

## Issue link

## Vercel preview

2024-03-04 15:12 UTC, sablevsky requested changes
У нас же нет буста сейчас в шапке? Только в модалке он живет?

2024-03-04 15:12 UTC, sablevsky commented on src/pages/LeaderboardPage/components/LinkWalletsModal/LinkWalletsModal.module.less
> +.linkedWalletBoost {
Можно сделать как Данил в своем ПРе.
https://github.com/frakt-solana/banx-ui/blob/f67ed942e8efd330bf53c78ad08ca0cc48b143e7/src/less/abstracts/variables.less#L80
Давай создадим еще переменную mds.
А то забудем все места где надо поменять. А так нужно будет только заменить mds на md

2024-03-04 15:47 UTC, iamsphere commented on src/pages/LeaderboardPage/components/LinkWalletsModal/LinkWalletsModal.module.less
> +.linkedWalletBoost {
md - 18px, mds - 16px
У нас тут нужно 14, smx?)

2024-03-04 15:50 UTC, iamsphere commented
> У нас же нет буста сейчас в шапке? Только в модалке он живет?
В шапке есть, приходит с бэка + выводим отдельно для каждого волета
![image](https://github.com/frakt-solana/banx-ui/assets/60342317/f7926347-419b-4f16-9a95-9dd2dfcd3b25)

2024-03-04 16:18 UTC, sablevsky commented on src/pages/LeaderboardPage/components/LinkWalletsModal/LinkWalletsModal.module.less
> +.linkedWalletBoost {
почему 3 разных размера шрифта. Егор...

2024-03-04 16:19 UTC, sablevsky commented
> > У нас же нет буста сейчас в шапке? Только в модалке он живет?
> > В шапке есть, приходит с бэка + выводим отдельно для каждого волета
> > ![image](https://private-user-images.githubusercontent.com/60342317/309815150-f7926347-419b-4f16-9a95-9dd2dfcd3b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjkzNjcsIm5iZiI6MTcwOTU2OTA2NywicGF0aCI6Ii82MDM0MjMxNy8zMDk4MTUxNTAtZjc5MjYzNDctNDE5Yi00ZjE2LTlhOTUtOWRkMmRmY2QzYjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE2MTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZGFkYmU1ODlhMjRmZWYwNTlhYzlmNThhYWQ3NmEyNjE5ZjkzYjM4NDE1OWZiMmIwM2QwMDljZWFmZmRkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyvpgpQcKgGS6iN17Ar4h0740UyVglqOecMcgUQss_0)

оно не складывается, полагаю? Ну ладно тогда

2024-03-04 16:19 UTC, sablevsky approved these changes

2024-03-05 07:31 UTC, iamsphere commented
> > > У нас же нет буста сейчас в шапке? Только в модалке он живет?
> > > В шапке есть, приходит с бэка + выводим отдельно для каждого волета
> > > ![image](https://private-user-images.githubusercontent.com/60342317/309815150-f7926347-419b-4f16-9a95-9dd2dfcd3b25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjkzNjcsIm5iZiI6MTcwOTU2OTA2NywicGF0aCI6Ii82MDM0MjMxNy8zMDk4MTUxNTAtZjc5MjYzNDctNDE5Yi00ZjE2LTlhOTUtOWRkMmRmY2QzYjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE2MTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZGFkYmU1ODlhMjRmZWYwNTlhYzlmNThhYWQ3NmEyNjE5ZjkzYjM4NDE1OWZiMmIwM2QwMDljZWFmZmRkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyvpgpQcKgGS6iN17Ar4h0740UyVglqOecMcgUQss_0)
> 
> оно не складывается, полагаю? Ну ладно тогда

В шапке складывается, вроде так и надо

2024-03-05 11:58 UTC, merged