Add fake infinite scroll for Tables on all pages
frakt-solana/banx-ui pull request #71
Opened 2023-09-05 20:01 UTC by iamsphere

## Description

## Screenshots

## Issue link

## Vercel preview

2023-09-05 22:08 UTC, sablevsky requested changes

2023-09-05 22:08 UTC, sablevsky commented on src/components/InfinityScroll/InfinityScroll.tsx
> +const InfinityScroll = ({
Давай типизируем через FC

2023-09-05 22:08 UTC, sablevsky commented on src/components/InfinityScroll/InfinityScroll.tsx
> +const InfinityScroll = ({
А нам вообще нужен этот компонент? Ты его вроде не заюзал нигде. И либа, соответственно

2023-09-06 07:35 UTC, iamsphere commented on src/components/InfinityScroll/InfinityScroll.tsx
> +const InfinityScroll = ({
Да, зря оставил, все можно и через useFakeInfinityScroll сделать
Перенес в src/hooks, либу удалил

2023-09-06 11:52 UTC, merged