BAN-2353: USDC loans
frakt-solana/banx-ui pull request #724
Opened 2024-04-03 12:38 UTC by iamsphere

## Description

## Screenshots

## Issue link

## Vercel preview

2024-04-08 11:40 UTC, sablevsky requested changes

2024-04-08 11:40 UTC, sablevsky commented on src/store/optimistics/useOffersOptimistic.ts
> +  return { optimisticOffers: filteredOffersByTokenType, add, remove, find, update }
Тут то же замечание/предложение, что и в useLoansOptimistc:
const type = isSolTokenType(tokenType) ? solLoans : usdcLoans
loan.bondTradeTransaction.lendingToken === type

2024-04-08 11:40 UTC, sablevsky commented on src/utils/accounts/index.ts
> +
я б лучше разделил на useWalletBalance и useUsdcBalance (можно сделать частным случаем useTokenBalance даже).
Внутри useWalletBalance использовать useUsdcBalance и useSolanaBalance и на основе tokenType возвращать нужный баланс.
Так логика станет полегче и архитектурно правильнее

2024-04-08 11:40 UTC, sablevsky commented on src/components/Buttons/WalletConnectButton.tsx
> +  const usdcBalance = useTokenBalance(USDC_ADDRESS, { isLive: isUsdcTokenType(tokenType) })
Вот эти вещи переписать можно с учетом моих правок в useTokenBalance. Из useTokenBalance возвращать еще и tokenType. Чтоб проще разметку рисовать без дополнительных вызовов useToken

2024-04-08 11:40 UTC, sablevsky commented on src/components/Buttons/WalletConnectButton.tsx
> +          {tokenType === LendingTokenType.NativeSol && <DisplayValue value={solanaBalance} />}
У тебя ж есть функции isSol и isUSDC

2024-04-08 11:40 UTC, sablevsky commented on src/components/PlaceOfferSection/hooks/usePlaceOffer.ts
> +  const usdcBalance = useTokenBalance(USDC_ADDRESS, { isLive: isUsdcTokenType(tokenType) })
А тут такой же прикол может быть с isLive для usdc (в сотни раз реже, но может). Думаю, можно выключить isLive, хуже не будет

2024-04-08 11:40 UTC, sablevsky commented on src/components/StatInfo/constants.tsx
> -  SOLPRICE = 'solPrice',
А почему ушли значения для соланы (и usdc соответственно)?
Имеет смысл тогда сделать type ReactNode, наверное

2024-04-08 11:40 UTC, sablevsky commented on src/components/TokenSwitcher/TokenSwitcher.tsx
> +  const tokenIcon = { [LendingTokenType.Usdc]: USDC, [LendingTokenType.NativeSol]: SOL }
Константы капсом и за пределы компонента можно

2024-04-08 11:40 UTC, sablevsky commented on src/store/useToken.ts
И я б переименовал на useTokenType, даже

2024-04-08 11:40 UTC, sablevsky commented on src/store/useToken.ts
> +  token: LendingTokenType
tokenType, setTokenType, toggleTokenType тогда лучше. А то у тебя почти во всех вызовах переименование идет

2024-04-08 11:40 UTC, sablevsky commented on src/pages/LendPage/hooks.ts
> +        marketPubkey: new web3.PublicKey(marketPubkey as string),
можно сделать  marketPubkey ?? web3.PublicKey.default. Чтоб избавиться от этого некрасивого явного приведения

2024-04-08 11:40 UTC, sablevsky commented on src/pages/LoansPage/components/LoansActiveTable/TableCells/ActionsCell/RefinanceModal.tsx
>    difference: number //? lamports
Получается, что уже не lamports (т.к. это только к солу относится). Можно в комменте написать 'integer representation of value'

2024-04-08 11:40 UTC, sablevsky commented on src/pages/LoansPage/hooks.ts
Мне кажется, что можно refetchInterval: 60 * 1000 в useWalletLoansAndOffers убрать, не так много от него пользы, а конфликта с оптимистиками больше. И нагрузка на бэк больше

2024-04-08 11:40 UTC, sablevsky commented on src/pages/LoansPage/hooks.ts
Хотя, давай просто побольше сделаем, для тех юзеров, которые не любят страницы закрывать в браузере: 5 * 1000

2024-04-08 11:46 UTC, iamsphere commented on src/utils/idb/index.ts
> +const BANX_LAST_IDB_PURGE_TIMESTAMP = '@banx.lastIdbPurgeTimestampV2'
Вычистит indexDb, так как поменялся нейминг

2024-04-08 12:06 UTC, iamsphere commented on src/api/core/types.ts
> +  bondTradeTransactionState: z.string(),
[Type BondTradeTransaction and FraktBond schemas with nativeEnum](https://github.com/frakt-solana/banx-ui/pull/724/commits/e06ffe8173102dfa6126e6bb5476e77199e7003c)

2024-04-08 12:08 UTC, iamsphere commented on src/store/optimistics/useLoansOptimistic.ts
> +  return { loans: filteredLoansByTokenType, add, remove, find, update }
[Improve efficiency by avoiding double filtering](https://github.com/frakt-solana/banx-ui/pull/724/commits/1eaaa23c23b6ec34dc0d8a224ad2cb2cf7330ce1)

2024-04-08 12:08 UTC, iamsphere commented on src/store/optimistics/useOffersOptimistic.ts
> +  return { optimisticOffers: filteredOffersByTokenType, add, remove, find, update }
[Improve efficiency by avoiding double filtering](https://github.com/frakt-solana/banx-ui/pull/724/commits/1eaaa23c23b6ec34dc0d8a224ad2cb2cf7330ce1)

2024-04-08 14:04 UTC, iamsphere commented on src/pages/LoansPage/components/LoansActiveTable/TableCells/ActionsCell/RefinanceModal.tsx
>    difference: number //? lamports
[Write better comment for "difference" prop](https://github.com/frakt-solana/banx-ui/pull/724/commits/76b6c46d7bf1e44e5423e4c31d1c5e0f6d229438)

2024-04-08 14:04 UTC, iamsphere commented on src/components/TokenSwitcher/TokenSwitcher.tsx
> +  const tokenIcon = { [LendingTokenType.Usdc]: USDC, [LendingTokenType.NativeSol]: SOL }
Extract constants outside of the component

2024-04-08 14:04 UTC, iamsphere commented on src/components/TokenSwitcher/TokenSwitcher.tsx
> +  const tokenIcon = { [LendingTokenType.Usdc]: USDC, [LendingTokenType.NativeSol]: SOL }
[Extract constants outside of the component](https://github.com/frakt-solana/banx-ui/pull/724/commits/af10dda611c584f9f26616582053bb47d7d48e7e)

2024-04-08 14:08 UTC, iamsphere commented on src/components/Buttons/WalletConnectButton.tsx
> +          {tokenType === LendingTokenType.NativeSol && <DisplayValue value={solanaBalance} />}
[Use isSolTokenType and isUsdcTokenType where it's needed](https://github.com/frakt-solana/banx-ui/pull/724/commits/a5c9d860983ba39728ccd13fce42962700f604b7)

2024-04-08 15:03 UTC, iamsphere commented on src/store/useToken.ts
[Rename "useToken" to "useTokenType"](https://github.com/frakt-solana/banx-ui/pull/724/commits/efc107f530594239277e79cd3ce4340aa04fc993)

2024-04-08 15:03 UTC, iamsphere commented on src/store/useToken.ts
> +  token: LendingTokenType
[Rename "useToken" to "useTokenType"](https://github.com/frakt-solana/banx-ui/pull/724/commits/efc107f530594239277e79cd3ce4340aa04fc993)

2024-04-08 16:14 UTC, iamsphere commented on src/utils/tokens/helpers.ts
> +const isValueBelowThreshold = (value: number, threshold: number) => value < threshold
Считаю что название подходит, оно точно описывает то, что делает эта функция.
Функция проверяет, меньше ли заданное значение (value) определенного порога (threshold).

2024-04-08 16:20 UTC, iamsphere commented on src/components/StatInfo/constants.tsx
> -  SOLPRICE = 'solPrice',
Теперь StatInfo не работает со значениями токена, вместо него этим занимается DisplayValue

2024-04-08 16:21 UTC, iamsphere commented on src/components/StatInfo/constants.tsx
> -  SOLPRICE = 'solPrice',
PERCENT нужен для форматирования

2024-04-08 16:40 UTC, iamsphere commented on src/pages/LoansPage/hooks.ts
[Increase refetchInterval to 5 minutes for useWalletLoansAndOffers](https://github.com/frakt-solana/banx-ui/pull/724/commits/6e536825c390cfdd688f5a4d6e87a17f80fc35d3)

2024-04-08 16:40 UTC, iamsphere commented on src/components/inputs/NumericStepInput.tsx
> +  postfix?: string | JSX.Element
[Replace "postfix" type to ReactNode in NumericStepInput](https://github.com/frakt-solana/banx-ui/pull/724/commits/7bccbbf2cf97f9260a7e1c267b7a5c5a9f9f9b0e)

2024-04-08 16:41 UTC, iamsphere commented on src/constants/config.ts
> +}
[Rename TOKEN_RENT_FEE and TOKEN_THRESHOLD, move TOKEN_RENT_FEE to utils](https://github.com/frakt-solana/banx-ui/pull/724/commits/79156d634d35579d3634e7de6930c0fa21014abc)

2024-04-08 16:41 UTC, iamsphere commented on src/utils/tokens/constants.tsx
> +}
[Rename TOKEN_RENT_FEE and TOKEN_THRESHOLD, move TOKEN_RENT_FEE to utils](https://github.com/frakt-solana/banx-ui/pull/724/commits/79156d634d35579d3634e7de6930c0fa21014abc)

2024-04-08 17:00 UTC, iamsphere commented on src/utils/tokens/helpers.ts
> +export const convertTokenValue = (value: number, tokenType: LendingTokenType) => {
[Add return types for all tokens helpers, rename convertTokenValue](https://github.com/frakt-solana/banx-ui/pull/724/commits/7140a65baf18dea67e77e990a6318a7d0fb0b106)

2024-04-08 17:00 UTC, iamsphere commented on src/utils/tokens/helpers.ts
[Add return types for all tokens helpers, rename convertTokenValue](https://github.com/frakt-solana/banx-ui/pull/724/commits/7140a65baf18dea67e77e990a6318a7d0fb0b106)

2024-04-08 17:02 UTC, iamsphere commented on src/utils/tokens/constants.tsx
> +}
Не понял почему лишний, используется для конверта типов sdk в типы для бэкенда
Перенес в api/core/helpers -- там более подходящее место

2024-04-08 17:03 UTC, iamsphere commented on src/utils/tokens/constants.tsx
> +}
[Move convertToMarketType to api requests helpers](https://github.com/frakt-solana/banx-ui/pull/724/commits/d34e62c1612e85977596de992dda3bf64672b5a4)

2024-04-08 17:26 UTC, iamsphere commented on src/store/useToken.ts
> +  }
Переписал его вообще в стиле usePriorityFees
usePriorityFees - хорошо написан)

[Rewrite useTokenType, move toggleTokenType in TokenSwitcher component](https://github.com/frakt-solana/banx-ui/pull/724/commits/0c1b6799576a3d3d7c70b0b912b7d53b5e263861)

2024-04-08 17:59 UTC, iamsphere commented on src/utils/accounts/index.ts
> +
[Implement useWalletBalance hook](https://github.com/frakt-solana/banx-ui/pull/724/commits/5c44873b58c71b2089af67c1be0ca77208620ed6)

2024-04-08 17:59 UTC, iamsphere commented on src/components/Buttons/WalletConnectButton.tsx
> +  const usdcBalance = useTokenBalance(USDC_ADDRESS, { isLive: isUsdcTokenType(tokenType) })
[Implement useWalletBalance hook](https://github.com/frakt-solana/banx-ui/pull/724/commits/5c44873b58c71b2089af67c1be0ca77208620ed6)

2024-04-08 17:59 UTC, iamsphere commented on src/utils/tokens/helpers.ts
> +}
[Add return types for all tokens helpers, rename convertTokenValue](https://github.com/frakt-solana/banx-ui/pull/724/commits/7140a65baf18dea67e77e990a6318a7d0fb0b106)

2024-04-08 18:07 UTC, iamsphere commented on src/pages/LendPage/hooks.ts
> +        marketPubkey: new web3.PublicKey(marketPubkey as string),
Вообще не понял зачем тут конвертить string в publicKey, а затем в fetchMarketOffers  опять в строку)

Передаю просто строку теперь 
[Change marketPubkey to string type for fetchMarketOffers request](https://github.com/frakt-solana/banx-ui/pull/724/commits/cd314a3ab8cc70043431a26350dc1ca0be470372)

2024-04-09 11:40 UTC, sablevsky commented on src/utils/tokens/constants.tsx
> +}
Если честно, так и не увидел, в какой модели с бэка используется этот MarketType

2024-04-09 11:43 UTC, sablevsky commented on src/utils/tokens/constants.tsx
> +}
MIN_TOKEN_VALUE_TO_DISPLAY предложу. Чуть покороче будет

2024-04-09 11:48 UTC, sablevsky commented on src/utils/tokens/constants.tsx
> +}
Отбой, увидел. Он для queryParams в запросе

2024-04-09 11:49 UTC, sablevsky approved these changes

2024-04-09 11:49 UTC, sablevsky commented on src/utils/tokens/helpers.ts
> +export const getTokenUnit = (tokenType: LendingTokenType): string | JSX.Element => {
Тут, наверное, тоже можно ReactNode использовать

2024-04-09 11:59 UTC, sablevsky commented on src/utils/tokens/constants.tsx
> +}
Даже MIN_VALUE_TO_DISPLAY будет достаточно

2024-04-09 12:09 UTC, iamsphere commented on src/utils/tokens/helpers.ts
> +export const getTokenUnit = (tokenType: LendingTokenType): string | JSX.Element => {
[Rename MINIMUM_DISPLAYABLE_TOKEN_VALUE, change return type for getTokenDecimals](https://github.com/frakt-solana/banx-ui/pull/724/commits/fb02568e1d7e7d8d3e6a5469afd89f81e5346bd9)

2024-04-09 12:15 UTC, iamsphere commented on src/utils/tokens/constants.tsx
> +}
[Rename MINIMUM_DISPLAYABLE_TOKEN_VALUE, change return type for getTokenDecimals](https://github.com/frakt-solana/banx-ui/pull/724/commits/fb02568e1d7e7d8d3e6a5469afd89f81e5346bd9)

2024-04-11 12:09 UTC, sablevsky approved these changes

2024-04-16 07:59 UTC, sablevsky approved these changes

2024-04-16 08:07 UTC, merged