BAN-2628: Implement new borrow ui on token lending
frakt-solana/banx-ui pull request #929
Opened 2024-08-19 07:34 UTC by iamsphere

## Description

## Screenshots

## Issue link

## Vercel preview

https://banx-ui-git-feature-ban-XXXX-frakt.vercel.app/

https://banx-ui-git-bugfix-ban-XXXX-frakt.vercel.app/

2024-08-19 08:41 UTC, sablevsky requested changes

2024-08-19 08:41 UTC, sablevsky commented on src/api/tokens/core/requests.ts
>  }
Давай напишем схему, чтоб валидировать оффера с бэка. Ну и тип в types.ts перенести тогда

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffers.ts
> +  const debouncedLtvSliderValue = useDebounceValue(ltvSliderValue, 1000)
давай 500мс выставим. Чтоб поотзывчивее было

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffers.ts
> +  })
давай уменьшим staleTime до 3-5 секунд. Думаю, тут особо не нужно кэшировать, т.к. нам критически важно доставать оффера как можно актуальнее

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useSelectedOffers.ts
> +  wallet: string
думаю, нет смысла хранить кошелек юзера. Оперировать BorrowOffer сразу

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useSelectedOffers.ts
> +}
тогда это не нужно делать

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffersTransaction.ts
> +  const { offers: offersByMarket, updateOrAddOffer } = useTokenMarketOffers(
переименуем в marketOffers. Так понятнее

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffersTransaction.ts
> +  const { offers: offersByMarket, updateOrAddOffer } = useTokenMarketOffers(
И давай вообще выпилим этот хук. У тебя достаточно данных для транзы из borrow-token-v4. Не нужно тянуть все. Market pubkey у тебя есть

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/helpers.ts
> +  const totalAmountToGet = new BN(sumBy(offers, (offer) => parseFloat(offer.maxTokenToGet)))
maxTokenToGet может не поместиться в parseFloat. Надо переписать подсчет суммы через BN.add и reduce

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/helpers.ts
> +  const amountToGetArray = offers.map((offer) => parseFloat(offer.maxTokenToGet))
maxTokenToGet может не поместиться в parseFloat. Нужно считать на BN

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/helpers.ts
> +  const maxOfferFunds = parseFloat(maxOffer.maxTokenToGet)
лучше переписать математику на BN

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/OrderBook.tsx
> +    } else {
Давай без else конструкции:
if (hasSelectedOffers) return clearSelection()
...

2024-08-19 08:41 UTC, sablevsky commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/OrderBook.tsx
> +      parseFloat(offer.offer.maxCollateralToReceive),
может не поместиться

2024-08-19 08:52 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffers.ts
> +  })
[Reduce stale time for borrow offers](https://github.com/frakt-solana/banx-ui/pull/929/commits/4e92557fe07d17be8aa88cc3a77097e8d659cd60)

2024-08-19 08:52 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffers.ts
> +  const debouncedLtvSliderValue = useDebounceValue(ltvSliderValue, 1000)
[Reduce stale time for borrow offers](https://github.com/frakt-solana/banx-ui/pull/929/commits/4e92557fe07d17be8aa88cc3a77097e8d659cd60)

2024-08-19 08:52 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useSelectedOffers.ts
> +  wallet: string
[Rewrite cart without wallet pubkey](https://github.com/frakt-solana/banx-ui/pull/929/commits/c4ecd4095d7728a47d70b631cd0ba08bea59d499)

2024-08-19 08:52 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useSelectedOffers.ts
> +}
[Rewrite cart without wallet pubkey](https://github.com/frakt-solana/banx-ui/pull/929/commits/c4ecd4095d7728a47d70b631cd0ba08bea59d499)

2024-08-19 08:59 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/hooks/useBorrowOffersTransaction.ts
> +  const { offers: offersByMarket, updateOrAddOffer } = useTokenMarketOffers(
Надо добавить сырой оффер в borrow-token-v4

2024-08-19 09:06 UTC, iamsphere commented on src/api/tokens/core/requests.ts
>  }
[Add BorrowOfferSchema schema](https://github.com/frakt-solana/banx-ui/pull/929/commits/aa336cb385ab84d8900042d7f92b98f3636daedc)

2024-08-19 09:16 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/OrderBook.tsx
> +    } else {
[Rewrite onSelectAll without else](https://github.com/frakt-solana/banx-ui/pull/929/commits/749faccb8e7172e0b6fd2a40751da544734bdf57)

2024-08-20 05:48 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/helpers.ts
> +  const totalAmountToGet = new BN(sumBy(offers, (offer) => parseFloat(offer.maxTokenToGet)))
771fbf5aff406ee6337d5d39da0eefe1ead079fd

2024-08-20 05:48 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/helpers.ts
> +  const amountToGetArray = offers.map((offer) => parseFloat(offer.maxTokenToGet))
771fbf5aff406ee6337d5d39da0eefe1ead079fd

2024-08-20 05:48 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/helpers.ts
> +  const maxOfferFunds = parseFloat(maxOffer.maxTokenToGet)
771fbf5aff406ee6337d5d39da0eefe1ead079fd

2024-08-20 05:48 UTC, iamsphere commented on src/pages/tokenLending/BorrowTokenPage/InstantBorrowContent/OrderBook/OrderBook.tsx
> +      parseFloat(offer.offer.maxCollateralToReceive),
771fbf5aff406ee6337d5d39da0eefe1ead079fd

2024-08-21 04:32 UTC, sablevsky approved these changes

2024-08-21 04:32 UTC, sablevsky commented on src/api/tokens/core/requests.ts
>    return data.data ?? []
у нас же есть parseResponseSafe для этих целей

2024-08-21 04:32 UTC, sablevsky commented on src/api/tokens/core/schemas.ts
> +})
Давай использовать StringIntSchema и StringPublicKeySchema, тогда схема читается сильно лучше

2024-08-21 04:32 UTC, sablevsky commented on src/utils/common/index.ts
> +export const convertAprToApy = (apr: number, compoundingPeriods: number = 1) => {
для второго параметра тип не нужен, т.к. значение по умолчанию 1

2024-08-21 04:32 UTC, sablevsky commented on src/components/PlaceTokenOfferSection/hooks/usePlaceTokenOffer.ts
> +export const MIN_LENDING_APR_RATE = 500
Не забудь спросить Глеба

2024-08-21 05:01 UTC, iamsphere commented on src/api/tokens/core/requests.ts
>    return data.data ?? []
10124a7c7d68102c0a9f7ab759b21d6265fb1e1e

2024-08-21 05:01 UTC, iamsphere commented on src/api/tokens/core/schemas.ts
> +})
10124a7c7d68102c0a9f7ab759b21d6265fb1e1e

2024-08-21 05:01 UTC, iamsphere commented on src/components/PlaceTokenOfferSection/hooks/usePlaceTokenOffer.ts
> +export const MIN_LENDING_APR_RATE = 500
10124a7c7d68102c0a9f7ab759b21d6265fb1e1e

2024-08-21 05:02 UTC, iamsphere commented on src/utils/common/index.ts
> +export const convertAprToApy = (apr: number, compoundingPeriods: number = 1) => {
10124a7c7d68102c0a9f7ab759b21d6265fb1e1e

2024-08-21 08:05 UTC, iamsphere commented on src/components/PlaceTokenOfferSection/hooks/usePlaceTokenOffer.ts
> +export const MIN_LENDING_APR_RATE = 500
[Import min and max apr token rate from SDK](https://github.com/frakt-solana/banx-ui/pull/929/commits/43c9ec8d44513283ce6b96a56f6d558ea66f3309)

2024-08-21 08:07 UTC, merged